# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
project 'CBBase58.xcodeproj'


# 去掉由pod引入的第三方库的警告，需要更新命令才生效
inhibit_all_warnings!

target 'CBBase58' do
    pod 'OpenSSL-Universal'


end
